### ISSUE TITLE
Fatal datapack errors

### ISSUE THREAD

**Issue by Darkhax** [Lemon-Juiced/SpookyStructures#1]
Hey, after updating to 1.0.2 I started receiving datapack errors when trying to load a world. Reverting to 1.0.1 resolves this issue.

Minecraft: 1.21.1
NeoForge: 21.1.74
SpookyStructures: 1.0.2

Log
[structure_error_log.log](https://github.com/user-attachments/files/17823865/structure_error_log.log)

**Comment by Lemon-Juiced** [comment]
Sorry about the mixup there, somehow an extra 0 entered the structure_set files, making the separation larger than the spacing. This issue should be resolved now as I've just tested it and pushed a new version.

**Comment by Lemon-Juiced** [comment]
The new version should be up on CurseForge as soon as its approved.

**Comment by Darkhax** [comment]
Awesome, thanks for quickly solving this issue!
